### ISSUE TITLE
Include San Francisco Font with Sketch files for download

### ISSUE THREAD

**Issue by mirshko** [bgian/Sketch-iOS-Library#1]
I seem to have downloaded the fonts from another Git Repo but they are not being recognized by your Sketch files. Do you mind including the ones you use?

**Comment by bgian** [comment]
Thanks for opening this @mirshko! As part of Apple's agreement, I don't think I'm allowed to send this font around publicly. I did a few things that should help fix this issue:

- [x] Updated the sketch files to use Apple's official font
- [x] Included a link in the `README.md` to download this font from Apple

Hopefully doing this will make sure the sketch files are using the same font everyone has!

**Comment by mirshko** [comment]
Sounds good!
