### ISSUE TITLE
Light & Dark Dropdown Fields

### ISSUE THREAD

**Issue by mirshko** [bgian/Sketch-iOS-Library#2]
Please add in Light / Dark Dropdown Fields

See: 
![screen shot 2016-11-29 at 9 27 46 am](https://cloud.githubusercontent.com/assets/8116716/20713406/27ca3ba0-b616-11e6-8bc4-e8cbd5181a4f.png)

**Comment by mirshko** [comment]
Also, We are unable to add labels to issues!

**Comment by bgian** [comment]
@mirshko 

> Please add in Light / Dark Dropdown Fields

I don't plan on adding components, just the smaller details like styles (e.g. blurs).

> Also, We are unable to add labels to issues!

I realized this is a limitation with GitHub, sorry! I've updated the `README.md` to remove adding labels as a step 😀

**Comment by mirshko** [comment]
Sounds good! Thanks again for this!
